steps:
# Install
  - name: 'grc.io/cloud-builders/npm'
    args: ['install']
# Build
  - name: 'grc.io/cloud-builders/ng'
    args: ['build']
# Deploy
  - name: 'grc.io/$PROJECT_ID/firebase'
    args: ['deploy']
