steps:
# Install
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
# Build
  - name: 'gcr.io/cloud-builders/ng:latest'
    args: ['build', '--prod']
# Deploy
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['deploy']
