version: 0.0
os: linux
files:
  - source: /server
    destination: /usr/ang-gal
permissions:
  - object: /usr/ang-gal/codedeploy
    pattern: "*.sh"
    owner: root
    group: root
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: codedeploy/before_install.sh
      timeout: 180
  AfterInstall:
    - location: codedeploy/after_install.sh
      timeout: 180
  ApplicationStart:
    - location: codedeploy/app_start.sh
      timeout: 180